/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as CasesCreatedIdRouteImport } from './routes/cases.created.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCreatedIdRoute = CasesCreatedIdRouteImport.update({
  id: '/created/$id',
  path: '/created/$id',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/cases/created/$id': typeof CasesCreatedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
  '/cases/created/$id': typeof CasesCreatedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/cases/created/$id': typeof CasesCreatedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/profile'
    | '/cases/$id'
    | '/cases/new'
    | '/cases/'
    | '/cases/created/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/cases/$id'
    | '/cases/new'
    | '/cases'
    | '/cases/created/$id'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/profile'
    | '/cases/$id'
    | '/cases/new'
    | '/cases/'
    | '/cases/created/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/created/$id': {
      id: '/cases/created/$id'
      path: '/created/$id'
      fullPath: '/cases/created/$id'
      preLoaderRoute: typeof CasesCreatedIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CasesCreatedIdRoute: typeof CasesCreatedIdRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
  CasesCreatedIdRoute: CasesCreatedIdRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
